version: 0.2
phases:
  install:
    runtime-versions:
       nodejs: 14
    commands:
      - npm install
      #- npm ci
      - sudo dnf install -y xorg-x11-server-Xvfb gtk3-devel nss alsa-lib
      - npx cypress cache clear
      - npm install cypress --save-dev
      - npm i --save-dev cypress-mochawesome-reporter
  pre_build:
    commands:
      - npx cypress verify
      - npx cypress info
  build:
    commands:
      - npx cypress run --e2e

artifacts:
  files:
    - "**/*"
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
cache:
  paths:
    - file1.txt
